services:
  mysql:
    build: .
    restart: always
    ports:
      - 3036:3036
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
  pma:
    depends_on:
     - mysql
    image: phpmyadmin:5.2
    restart: always
    ports:
     - 8080:80
    environment:
      PMA_HOST: mysql